using System;
using System.Collections.Generic;
using System.Text;

namespace Krkal.GEn
{
	static class TestLevel
	{
		public static String[,] level = {{
		 "                    ",  // steny
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
										 },{
		 "                    ",  
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
										 },{
		 "                    ",  // steny
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
										 },{
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
										 },{
		 "                    ",  // steny
		 "   SSSSS            ",
		 "     k S            ",
		 "       S            ",
		 "                    ",
		 "      SSSSSS  SSSSS ",
		 "              S   S ",
		 "              S   S ",
		 "              Z   S ",
		 "              S   S ",
		 "              SSSSS ",
		 "                    ",
		 "                    ",
		 "           SSSSS    ",
		 "           S   S    ",
		 "           S   S    ",
		 "           SSSSS    ",
										 },{
		 "   PPPPPP           ",
		 "   PPPPPP           ",
		 "   PPPPPP           ",
		 "   PPPPPP           ",
		 "                    ",
		 "              PPPPP ",
		 "      SSSSSS  PPPPP ",
		 "              PPPPP ",
		 "              PPPPP ",
		 "              PPPPP ",
		 "              PPPPP ",
		 "                    ",
		 "                    ",
		 "           PPPPP    ",
		 "           PPPPP    ",
		 "           PPPPP    ",
		 "           PPPPP    ",
										 },{
		 "                    ",   // steny
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
										 },{
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",
		 "                    ",

	    }};
	}
}
